/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs_.$runId'
import { Route as DocsCustomImagesRouteImport } from './routes/docs.custom-images'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCustomImagesRoute = DocsCustomImagesRouteImport.update({
  id: '/docs/custom-images',
  path: '/docs/custom-images',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evals': typeof EvalsRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/custom-images': typeof DocsCustomImagesRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evals': typeof EvalsRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/custom-images': typeof DocsCustomImagesRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evals': typeof EvalsRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/docs/custom-images': typeof DocsCustomImagesRoute
  '/runs_/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evals'
    | '/runs'
    | '/skills'
    | '/workflows'
    | '/docs/custom-images'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evals'
    | '/runs'
    | '/skills'
    | '/workflows'
    | '/docs/custom-images'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/evals'
    | '/runs'
    | '/skills'
    | '/workflows'
    | '/docs/custom-images'
    | '/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvalsRoute: typeof EvalsRoute
  RunsRoute: typeof RunsRoute
  SkillsRoute: typeof SkillsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  DocsCustomImagesRoute: typeof DocsCustomImagesRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs_/$runId': {
      id: '/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/custom-images': {
      id: '/docs/custom-images'
      path: '/docs/custom-images'
      fullPath: '/docs/custom-images'
      preLoaderRoute: typeof DocsCustomImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvalsRoute: EvalsRoute,
  RunsRoute: RunsRoute,
  SkillsRoute: SkillsRoute,
  WorkflowsRoute: WorkflowsRoute,
  DocsCustomImagesRoute: DocsCustomImagesRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
